# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'A Lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A Lodjinha
	pod 'Alamofire', '~> 4.0.0'
	pod 'SDWebImage', '5.0.0-beta3'
	pod 'SwiftyJSON', '~> 4.2'
  target 'A LodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'A LodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
